export const projects = [
  {
    title: 'GPT3-OpenbAI',
    // description: "Using React, Node.js, Express & MongoDB you'll learn how to build a Full Stack MERN Application - from start to finish. The App is called Memories and it is a simple social media app that allows users to post interesting events that happened in their lives.",
    image: '/images/gpt3.png',
    tags: ['React', 'JavaScript', 'Redux'],
    source: 'https://ai-gpt.netlify.app/',
    visit: 'https://github.com/khichibhavesh/GPT3-OpenbAI',
    id: 0,
  },
  {
    title: 'Gericht The Restaurant',
    // description:"While building it you're going to learn many advanced React & JavaScript topics, as well as how to use Stripe for card transactions. On top of that, at the end of the video, you will have this unique and complex webshop app that you will be able to add to your portfolio. And trust me, e-commerce applications are impressive.",
    image: '/images/restaurant.png',
    tags: ['React', 'JavaScript', 'Redux'],
    source: 'https://restat.netlify.app/',
    visit: 'https://github.com/khichibhavesh/restaurant-website',
    id: 1,
  },
  {
    title: 'HooBank',
    // description: "This is a code repository for the corresponding YouTube video. In this tutorial, we're going to build and deploy a React Video Chat Application using WebRTC.",
    image: '/images/bank.png',
    tags: ['React', 'JavaScript', 'Redux'],
    source: 'https://bank-m.netlify.app/',
    visit: 'https://github.com/khichibhavesh/hoobank-business',
    id: 2,
  },
  {
    title: 'React Dashbourd',
    // description: "This is a code repository for the corresponding video tutorial. In this video, we will create a full Realtime Chat Application",
    image: '/images/dashbourd.png',
    tags: ['React', 'JavaScript', 'Redux'],
    source: 'https://google.com',
    visit: 'https://github.com/khichibhavesh/react-dashbourd',
    id: 3,
  },
  {
    title: 'React Admin Dashboard',
    // description: "This is a code repository for the corresponding video tutorial. In this video, we will create a full Realtime Chat Application",
    image: '/images/admin.png',
    tags: ['React', 'JavaScript', 'Redux'],
    source: 'https://lamadmin.netlify.app/',
    visit: 'https://github.com/khichibhavesh/React-Admin-Dashboard',
    id: 4,
  },
];

export const TimeLineData = [
  // { year: 2017, text: 'Started my journey', },
  // { year: 2018, text: 'Worked as a freelance developer', },
  // { year: 2019, text: '', },
  // { year: 2020, text: 'Shared my projects with the world', },
  // { year: 2021, text: 'Started my own platform', },
];